apiVersion: v2
appVersion: "1.0"
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://tip.jfrog.io/artifactory/tip-wlan-cloud-ucentral-helm/
  version: 10.9.2
- condition: mysql.enabled
  name: mysql
  repository: https://tip.jfrog.io/artifactory/tip-wlan-cloud-ucentral-helm/
  version: 8.8.3
- condition: mariadb.enabled
  name: mariadb
  repository: https://tip.jfrog.io/artifactory/tip-wlan-cloud-ucentral-helm/
  version: 9.4.2
description: A Helm chart for Kubernetes
name: owfms
version: 0.1.0
